-- SQL script to insert products into the products table
-- Run this in the Supabase SQL Editor

INSERT INTO public.products (id, name, description, price, original_price, rating, review_count, image, images, category, brand, features, in_stock, tags, created_at)
VALUES
  -- Product 1
  (gen_random_uuid(), 'Inspirational Wall Art', 'tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in', 
   932.46, NULL, 3.4, 100, 
   'http://dummyimage.com/244x100.png/cc0000/ffffff', 
   ARRAY['http://dummyimage.com/244x100.png/cc0000/ffffff'], 
   'Home', 'Fivebridge', 
   ARRAY['Weight: 0.9', 'Dimensions: in tempor turpis nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc', 'Released: 12/7/2018', 'Featured: true'], 
   TRUE, 
   ARRAY['Decorative Wall Art & Accessories'], 
   NOW()),

  -- Product 2
  (gen_random_uuid(), 'Mango Chutney', 'mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum', 
   138.39, NULL, 4.3, 120, 
   'http://dummyimage.com/183x100.png/cc0000/ffffff', 
   ARRAY['http://dummyimage.com/183x100.png/cc0000/ffffff'], 
   'Food - Condiments', 'Abata', 
   ARRAY['Weight: 7.9', 'Dimensions: consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo', 'Released: 9/2/2013', 'Featured: true'], 
   TRUE, 
   ARRAY['Fruit Chutneys'], 
   NOW()),

  -- Product 3
  (gen_random_uuid(), 'Travel Pillow', 'id consequat in consequat ut nulla sed accumsan felis ut at', 
   967.81, 409.26, 1.8, 85, 
   'http://dummyimage.com/245x100.png/cc0000/ffffff', 
   ARRAY['http://dummyimage.com/245x100.png/cc0000/ffffff'], 
   'Travel', 'Dabtype', 
   ARRAY['Weight: 8.8', 'Dimensions: sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus', 'Released: 7/8/2013', 'On Sale: true'], 
   TRUE, 
   ARRAY['Travel Accessories'], 
   NOW()),

  -- Product 4
  (gen_random_uuid(), 'Gluten-Free Pancake Mix', 'sed vestibulum sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus', 
   920.89, 902.07, 3.3, 95, 
   'http://dummyimage.com/220x100.png/dddddd/000000', 
   ARRAY['http://dummyimage.com/220x100.png/dddddd/000000'], 
   'Food - Baking Goods', 'Devbug', 
   ARRAY['Weight: 5.9', 'Dimensions: et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum', 'Released: 3/31/2015', 'On Sale: true'], 
   TRUE, 
   ARRAY['Baking Mixes'], 
   NOW()),

  -- Product 5
  (gen_random_uuid(), 'Dog Collar', 'tellus in sagittis dui vel nisl duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse', 
   238.65, NULL, 4.5, 150, 
   'http://dummyimage.com/135x100.png/dddddd/000000', 
   ARRAY['http://dummyimage.com/135x100.png/dddddd/000000'], 
   'Pets', 'Devbug', 
   ARRAY['Weight: 2.7', 'Dimensions: nulla dapibus dolor vel est donec odio justo sollicitudin ut', 'Released: 3/31/2021'], 
   TRUE, 
   ARRAY['Dog Accessories'], 
   NOW()),

  -- Product 6
  (gen_random_uuid(), 'Handheld Garment Steamer', 'fermentum justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit', 
   936.36, 922.32, 3.8, 110, 
   'http://dummyimage.com/103x100.png/5fa2dd/ffffff', 
   ARRAY['http://dummyimage.com/103x100.png/5fa2dd/ffffff'], 
   'Home', 'Browsezoom', 
   ARRAY['Weight: 3.5', 'Dimensions: integer non velit donec diam neque vestibulum eget vulputate ut', 'Released: 5/15/2020', 'Featured: true', 'On Sale: true'], 
   TRUE, 
   ARRAY['Home Appliances'], 
   NOW()),

  -- Product 7
  (gen_random_uuid(), 'Spinach Artichoke Dip', 'donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris', 
   988.9, NULL, 2.3, 75, 
   'http://dummyimage.com/115x100.png/5fa2dd/ffffff', 
   ARRAY['http://dummyimage.com/115x100.png/5fa2dd/ffffff'], 
   'Food - Snacks', 'Gabspot', 
   ARRAY['Weight: 6', 'Dimensions: diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi', 'Released: 1/31/2011'], 
   TRUE, 
   ARRAY['Dips and Spreads'], 
   NOW()),

  -- Product 8
  (gen_random_uuid(), 'Canvas High-Top Sneakers', 'nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec', 
   314.04, 157.21, 2.2, 80, 
   'http://dummyimage.com/217x100.png/dddddd/000000', 
   ARRAY['http://dummyimage.com/217x100.png/dddddd/000000'], 
   'Clothing - Footwear', 'Ozu', 
   ARRAY['Weight: 8.2', 'Dimensions: nec euismod scelerisque quam turpis adipiscing lorem vitae mattis nibh ligula', 'Released: 6/3/2012', 'On Sale: true'], 
   TRUE, 
   ARRAY['Casual Footwear'], 
   NOW()),

  -- Product 9
  (gen_random_uuid(), 'Soft Plush Throw Blanket', 'sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus at diam nam tristique tortor', 
   571.08, 171.39, 4.4, 135, 
   'http://dummyimage.com/168x100.png/cc0000/ffffff', 
   ARRAY['http://dummyimage.com/168x100.png/cc0000/ffffff'], 
   'Home', 'Browsebug', 
   ARRAY['Weight: 6.1', 'Dimensions: dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum at', 'Released: 9/13/2011', 'On Sale: true'], 
   TRUE, 
   ARRAY['Bedding & Linens'], 
   NOW()),

  -- Product 10
  (gen_random_uuid(), 'Digital Drawing Tablet', 'turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu est', 
   944.38, 248.7, 3.4, 105, 
   'http://dummyimage.com/165x100.png/cc0000/ffffff', 
   ARRAY['http://dummyimage.com/165x100.png/cc0000/ffffff'], 
   'Art Supplies', 'Topicshots', 
   ARRAY['Weight: 7.8', 'Dimensions: phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in', 'Released: 9/14/2016', 'On Sale: true'], 
   TRUE, 
   ARRAY['Digital Art Supplies'], 
   NOW()),

  -- Product 11
  (gen_random_uuid(), 'Foot Spa Bath Massager', 'massa volutpat convallis morbi odio odio elementum eu interdum eu', 
   92.23, NULL, 1.8, 65, 
   'http://dummyimage.com/166x100.png/cc0000/ffffff', 
   ARRAY['http://dummyimage.com/166x100.png/cc0000/ffffff'], 
   'Health', 'Skibox', 
   ARRAY['Weight: 0.1', 'Dimensions: nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim', 'Released: 10/29/2015', 'Featured: true'], 
   TRUE, 
   ARRAY['Personal Care & Grooming'], 
   NOW()),

  -- Product 12
  (gen_random_uuid(), 'Natural Peanut Butter', 'massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet', 
   498.23, NULL, 1.2, 55, 
   'http://dummyimage.com/123x100.png/cc0000/ffffff', 
   ARRAY['http://dummyimage.com/123x100.png/cc0000/ffffff'], 
   'Food - Spreads', 'Camido', 
   ARRAY['Weight: 8.7', 'Dimensions: est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis', 'Released: 2/22/2013'], 
   TRUE, 
   ARRAY['Nut Butters'], 
   NOW()),

  -- Product 13
  (gen_random_uuid(), 'Bock Beer Mustard', 'ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque', 
   774.43, NULL, 2.5, 85, 
   'http://dummyimage.com/138x100.png/ff4444/ffffff', 
   ARRAY['http://dummyimage.com/138x100.png/ff4444/ffffff'], 
   'Food - Condiments', 'Plambee', 
   ARRAY['Weight: 6.3', 'Dimensions: ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl venenatis', 'Released: 1/12/2014', 'Featured: true'], 
   TRUE, 
   ARRAY['Mustards'], 
   NOW()),

  -- Product 14
  (gen_random_uuid(), 'Sriracha Honey Glaze', 'integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat', 
   281.65, NULL, 2.0, 70, 
   'http://dummyimage.com/128x100.png/cc0000/ffffff', 
   ARRAY['http://dummyimage.com/128x100.png/cc0000/ffffff'], 
   'Food - Sauces', 'Ntags', 
   ARRAY['Weight: 7.4', 'Dimensions: consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac', 'Released: 5/15/2013'], 
   TRUE, 
   ARRAY['Condiments'], 
   NOW()),

  -- Product 15
  (gen_random_uuid(), 'Multifunctional Baby Bottle Warmer', 'ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus', 
   651.62, 691.63, 3.5, 95, 
   'http://dummyimage.com/243x100.png/cc0000/ffffff', 
   ARRAY['http://dummyimage.com/243x100.png/cc0000/ffffff'], 
   'Baby', 'Youtags', 
   ARRAY['Weight: 0.9', 'Dimensions: ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero', 'Released: 6/30/2021', 'On Sale: true'], 
   TRUE, 
   ARRAY['Feeding Accessories'], 
   NOW()),

  -- Product 16
  (gen_random_uuid(), 'Pet Activity Tracker', 'justo morbi ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in blandit', 
   493.83, NULL, 1.7, 60, 
   'http://dummyimage.com/145x100.png/5fa2dd/ffffff', 
   ARRAY['http://dummyimage.com/145x100.png/5fa2dd/ffffff'], 
   'Pets', 'Oyoba', 
   ARRAY['Weight: 6.4', 'Dimensions: gravida nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum', 'Released: 8/6/2017', 'Featured: true'], 
   TRUE, 
   ARRAY['Pet Health and Care'], 
   NOW()),

  -- Product 17
  (gen_random_uuid(), 'Travel Shoe Bags Set', 'in eleifend quam a odio in hac habitasse platea dictumst maecenas ut', 
   730.66, 593.56, 4.8, 140, 
   'http://dummyimage.com/117x100.png/ff4444/ffffff', 
   ARRAY['http://dummyimage.com/117x100.png/ff4444/ffffff'], 
   'Travel', 'Twitterbeat', 
   ARRAY['Weight: 5.8', 'Dimensions: in porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum', 'Released: 10/20/2011', 'Featured: true', 'On Sale: true'], 
   TRUE, 
   ARRAY['Travel Accessories'], 
   NOW()),

  -- Product 18
  (gen_random_uuid(), 'Electric Griddle with Lid', 'in porttitor pede justo eu massa donec dapibus duis at velit eu est congue elementum in', 
   652.75, 42.93, 1.7, 60, 
   'http://dummyimage.com/234x100.png/dddddd/000000', 
   ARRAY['http://dummyimage.com/234x100.png/dddddd/000000'], 
   'Kitchen', 'Divanoodle', 
   ARRAY['Weight: 3.3', 'Dimensions: tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque', 'Released: 10/29/2016', 'Featured: true', 'On Sale: true'], 
   TRUE, 
   ARRAY['Cooking Appliances'], 
   NOW()),

  -- Product 19
  (gen_random_uuid(), 'Digital Wireless Camera', 'amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at nulla suspendisse', 
   7.05, NULL, 2.0, 70, 
   'http://dummyimage.com/105x100.png/dddddd/000000', 
   ARRAY['http://dummyimage.com/105x100.png/dddddd/000000'], 
   'Home Security', 'Dynabox', 
   ARRAY['Weight: 1.2', 'Dimensions: quis odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero non mattis pulvinar', 'Released: 12/22/2013', 'Featured: true'], 
   TRUE, 
   ARRAY['Cameras'], 
   NOW()),

  -- Product 20
  (gen_random_uuid(), 'Personal Blender with Cups', 'magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque', 
   382.98, 475.39, 4.7, 130, 
   'http://dummyimage.com/167x100.png/5fa2dd/ffffff', 
   ARRAY['http://dummyimage.com/167x100.png/5fa2dd/ffffff'], 
   'Kitchen', 'Mydeo', 
   ARRAY['Weight: 5.2', 'Dimensions: ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam', 'Released: 9/9/2016', 'Featured: true', 'On Sale: true'], 
   TRUE, 
   ARRAY['Blenders & Juicers'], 
   NOW()),

  -- Product 21
  (gen_random_uuid(), 'Chicken Fajita Kit', 'maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum', 
   966.57, NULL, 4.1, 125, 
   'http://dummyimage.com/153x100.png/ff4444/ffffff', 
   ARRAY['http://dummyimage.com/153x100.png/ff4444/ffffff'], 
   'Food - Prepared Foods', 'Plajo', 
   ARRAY['Weight: 6.4', 'Dimensions: ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie', 'Released: 1/27/2015'], 
   TRUE, 
   ARRAY['Meal Kits'], 
   NOW()),

  -- Product 22
  (gen_random_uuid(), 'Waterproof Rain Boots', 'aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero', 
   929.86, NULL, 1.8, 65, 
   'http://dummyimage.com/235x100.png/5fa2dd/ffffff', 
   ARRAY['http://dummyimage.com/235x100.png/5fa2dd/ffffff'], 
   'Clothing - Footwear', 'Vitz', 
   ARRAY['Weight: 7.7', 'Dimensions: quam turpis adipiscing lorem vitae mattis nibh ligula nec sem duis aliquam convallis nunc proin at turpis', 'Released: 7/3/2018', 'Featured: true'], 
   TRUE, 
   ARRAY['Rain Footwear'], 
   NOW()),

  -- Product 23
  (gen_random_uuid(), 'Classic Cheesecake Mix', 'consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor', 
   783.28, NULL, 3.5, 100, 
   'http://dummyimage.com/192x100.png/dddddd/000000', 
   ARRAY['http://dummyimage.com/192x100.png/dddddd/000000'], 
   'Food - Desserts', 'Blogtag', 
   ARRAY['Weight: 9.5', 'Dimensions: amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue', 'Released: 3/26/2021'], 
   TRUE, 
   ARRAY['Baking Mixes'], 
   NOW()),

  -- Product 24
  (gen_random_uuid(), 'Carrot Sticks', 'est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin', 
   851.31, 265.52, 3.4, 95, 
   'http://dummyimage.com/196x100.png/ff4444/ffffff', 
   ARRAY['http://dummyimage.com/196x100.png/ff4444/ffffff'], 
   'Food - Produce', 'Yamia', 
   ARRAY['Weight: 3.2', 'Dimensions: sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit amet', 'Released: 10/8/2011', 'On Sale: true'], 
   TRUE, 
   ARRAY['Vegetable Snacks'], 
   NOW()),

  -- Product 25
  (gen_random_uuid(), 'Home Delivery Food Journal', 'pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu', 
   250.45, 193.36, 3.2, 90, 
   'http://dummyimage.com/176x100.png/5fa2dd/ffffff', 
   ARRAY['http://dummyimage.com/176x100.png/5fa2dd/ffffff'], 
   'Health', 'Skibox', 
   ARRAY['Weight: 4.5', 'Dimensions: porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris', 'Released: 1/21/2014', 'Featured: true', 'On Sale: true'], 
   TRUE, 
   ARRAY['Nutrition & Fitness'], 
   NOW()),

  -- Product 26
  (gen_random_uuid(), 'Herb Seasoned Couscous', 'in felis donec semper sapien a libero nam dui proin leo odio porttitor id', 
   905.4, NULL, 4.4, 130, 
   'http://dummyimage.com/135x100.png/cc0000/ffffff', 
   ARRAY['http://dummyimage.com/135x100.png/cc0000/ffffff'], 
   'Food - Grains', 'Roombo', 
   ARRAY['Weight: 8.8', 'Dimensions: consequat varius integer ac leo pellentesque ultrices mattis odio donec', 'Released: 9/18/2018'], 
   TRUE, 
   ARRAY['Flavored Couscous'], 
   NOW()),

  -- Product 27
  (gen_random_uuid(), 'Bamboo Toothbrush', 'nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem', 
   60.38, NULL, 1.1, 50, 
   'http://dummyimage.com/224x100.png/5fa2dd/ffffff', 
   ARRAY['http://dummyimage.com/224x100.png/5fa2dd/ffffff'], 
   'Health', 'Edgepulse', 
   ARRAY['Weight: 7.6', 'Dimensions: ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse', 'Released: 5/17/2013'], 
   TRUE, 
   ARRAY['Oral Care & Hygiene'], 
   NOW()),

  -- Product 28
  (gen_random_uuid(), 'Self-Massaging Pillow', 'aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam', 
   549.79, 966.43, 4.6, 135, 
   'http://dummyimage.com/183x100.png/ff4444/ffffff', 
   ARRAY['http://dummyimage.com/183x100.png/ff4444/ffffff'], 
   'Health', 'Fiveclub', 
   ARRAY['Weight: 3.5', 'Dimensions: vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas', 'Released: 4/23/2020', 'Featured: true', 'On Sale: true'], 
   TRUE, 
   ARRAY['Sleep & Relaxation'], 
   NOW()),

  -- Product 29
  (gen_random_uuid(), 'Pet Reflective Vest', 'phasellus in felis donec semper sapien a libero nam dui proin leo odio porttitor id consequat in consequat ut', 
   140.13, NULL, 3.7, 105, 
   'http://dummyimage.com/236x100.png/dddddd/000000', 
   ARRAY['http://dummyimage.com/236x100.png/dddddd/000000'], 
   'Pets', 'Zoozzy', 
   ARRAY['Weight: 3.6', 'Dimensions: aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse', 'Released: 8/4/2015', 'Featured: true'], 
   TRUE, 
   ARRAY['Pet Safety Gear'], 
   NOW()),

  -- Product 30
  (gen_random_uuid(), 'Set of Measuring Spoons', 'vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus', 
   702.13, 45.06, 3.3, 95, 
   'http://dummyimage.com/228x100.png/dddddd/000000', 
   ARRAY['http://dummyimage.com/228x100.png/dddddd/000000'], 
   'Kitchen', 'Feedmix', 
   ARRAY['Weight: 1.9', 'Dimensions: suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut mauris eget massa', 'Released: 7/23/2018', 'On Sale: true'], 
   TRUE, 
   ARRAY['Kitchen Gadgets'], 
   NOW()),

  -- Product 31
  (gen_random_uuid(), 'Chocolate Mint Thins', 'lorem ipsum dolor sit amet consectetuer adipiscing elit proin risus praesent lectus vestibulum quam sapien varius ut blandit', 
   332.04, 738.22, 5.0, 150, 
   'http://dummyimage.com/142x100.png/ff4444/ffffff', 
   ARRAY['http://dummyimage.com/142x100.png/ff4444/ffffff'], 
   'Food - Snacks', 'Photolist', 
   ARRAY['Weight: 2', 'Dimensions: curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien', 'Released: 4/18/2022', 'On Sale: true'], 
   TRUE, 
   ARRAY['Candy'], 
   NOW()),

  -- Product 32
  (gen_random_uuid(), 'Pet Water Fountain', 'ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit', 
   331.67, 105.28, 4.1, 125, 
   'http://dummyimage.com/138x100.png/cc0000/ffffff', 
   ARRAY['http://dummyimage.com/138x100.png/cc0000/ffffff'], 
   'Pets', 'Tambee', 
   ARRAY['Weight: 8.7', 'Dimensions: nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis justo', 'Released: 12/26/2018', 'Featured: true', 'On Sale: true'], 
   TRUE, 
   ARRAY['Pet Supplies'], 
   NOW()); 