// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jafvoubzwzwfxtkkeyqx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImphZnZvdWJ6d3p3Znh0a2tleXF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NTU4ODEsImV4cCI6MjA2NzEzMTg4MX0.svNP2yniAWIk5M8IdNZHhSdzeVztk5U2yziQOVG0uUY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});